export { desktopApi } from './api'
export type { DesktopApi } from './api'
export { desktopEvents } from './events'
export type { DesktopEvents } from './events'
export { DesktopCommandError, normalizeDesktopError } from './errors'
export type * from './generated/contracts'
