// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DraftImageAttachment } from "./DraftImageAttachment";
import type { SessionImageAttachment } from "./SessionImageAttachment";

export type ComposerImageAttachment = { "scope": "session" } & SessionImageAttachment | { "scope": "draft" } & DraftImageAttachment;
