// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionImageAttachment = { id: string, kind: string, name: string, mimeType: string, width: number, height: number, sizeBytes: bigint, storageKey: string, scope: string, sessionId: string, };
