use std::{fs, path::PathBuf};

use codez_contracts::{
    CommandError, DesktopEvent, ErrorCode, HealthResponse, SystemProbeEvent, ThemeInfo,
    ThemeSource, WindowAction,
};
use ts_rs::{Config, TS};

fn main() -> std::io::Result<()> {
    let workspace_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()?;
    let output_dir = workspace_root.join("src/renderer/src/shared/desktop/generated");
    fs::create_dir_all(&output_dir)?;
    let config = Config::default();

    let declarations = [
        "// Generated by `npm run contracts:generate`. Do not edit by hand.\n".to_string(),
        format!("export {}", ErrorCode::decl(&config)),
        format!("export {}", CommandError::decl(&config)),
        format!("export {}", HealthResponse::decl(&config)),
        format!("export {}", SystemProbeEvent::decl(&config)),
        format!("export {}", WindowAction::decl(&config)),
        format!("export {}", ThemeSource::decl(&config)),
        format!("export {}", ThemeInfo::decl(&config)),
        format!("export {}", DesktopEvent::<String>::decl(&config)),
    ]
    .join("\n\n");

    fs::write(output_dir.join("contracts.ts"), format!("{declarations}\n"))
}
